##### openrouteservice settings file #####
# This file contains parameters for openrouteservice.
# For a full list of possible parameters see https://giscience.github.io/openrouteservice/run-instance/configuration/

ors:
  engine:
    source_file: /home/ors/files/data.osm.pbf
    elevation:
      # Disabling elevation for now because ORS tries to download
      # elevation data from URL's that are not always available,
      # which sometimes raises SocketTimeoutException's and prevents
      # ORS from starting. See
      # https://github.com/GIScience/openrouteservice/issues?q=is%3Aissue+java.net.SocketTimeoutException
      # for more info
      preprocessed: true

    profiles:
      car:
       enabled: true
       elevation: false

      hgv:
       enabled: true
       profile: driving-hgv
       encoder_flags_size: 8
       encoder_options:
         turn_costs: true
         block_fords: false
         use_acceleration: true
       maximum_distance: 100000
       elevation: false
       preparation:
         min_network_size: 200
         methods:
           ch:
             enabled: true
             threads: 1
             weightings: recommended
           core:
             enabled: true
             threads: 1
             weightings: recommended,shortest
             landmarks: 64
             lmsets: highways;allow_all
       execution:
         methods:
           core:
             active_landmarks: 6
       ext_storages:
         WayCategory:
         HeavyVehicle:
           restrictions: true
         WaySurfaceType:

logging:
  level:
    root: DEBUG
    org:
      heigit: INFO
