name: Deploy to Dev

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  schedule:
    # Runs every Monday and Thursday at 15:39 UTC, which is either
    # 8:49 AM or 9:49 AM ET, depending on Daylight Savings Time. This
    # is two hours before the prod deploy, so we can see how dev is
    # doing before approving a prod deploy.
    - cron: "49 13 * * 1,4"

jobs:
  call-workflow:
    uses: mbta/workflows/.github/workflows/deploy-ecs.yml@v2
    with:
      app-name: ors
      environment: dev
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
      docker-repo: ${{ secrets.DOCKER_REPO }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
